
name: Build and Deploy fsservice to GKE

on:
  push:
    paths:
        - filestorage/service/**
  workflow_dispatch:

env:
  PROJECT_ID: noted-flash-366811
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  GAR_LOCATION: europe-west4
  GKE_CLUSTER: noted-flash-366811-gke
  GKE_ZONE: europe-west4
  REPOSITORY: services-repository
  FS_SERVICE_IMAGE: fs_service
  FS_DB_USER: ${{ secrets.FS_DB_USER }}
  FS_DB_PASS: ${{ secrets.FS_DB_PASS }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}

    - name: Docker configuration
      run: |-
        echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "eu.gcr.io/$PROJECT_ID/$FS_SERVICE_IMAGE" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          ./filestorage/service

    - name: Helper
      run: |
       gcloud auth configure-docker -q

    - name: Delete old image in GCR
      run: |
       gcloud container images delete eu.gcr.io/$PROJECT_ID/$FS_SERVICE_IMAGE || true

    - name: Push to GCR
      run: |-
       docker push eu.gcr.io/$PROJECT_ID/$FS_SERVICE_IMAGE



    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        envsubst < filestorage/DB/postgres-deployment.yaml | kubectl apply -f -
        envsubst < filestorage/fs-deployment.yaml | kubectl apply -f -
        kubectl rollout status deployment/fs-postgres
        kubectl rollout status deployment/fs-service
