name: Release
on:
  workflow_run:
    branches:
    - release
    workflows: [ "Test" ]
    types:
      - completed

permissions: write-all
jobs:
  pre-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release Build"
          files: |
            *
